Middleware docs for Montenegro
fiskaltrust/interface-doc pull request #238
Opened 2022-05-02 14:51 UTC by TSchmiedlechner

A first draft of the middleware interface documentation for Montenegro.

- [ ] Introduction
- [ ] Reference tables
- [ ] Terminology
- [ ] Installation
- [ ] ...

2022-09-22 12:24 UTC, mijomilicevic requested changes

2022-09-22 12:24 UTC, mijomilicevic commented on doc/appendix-me/appendix-me.md
> +<div class="alert alert--warning" role="alert">Please note that this information is only complete when combined with the <b>General</b> part. To implement the Middleware, users should get themselves
```suggestion
---
slug: /poscreators/middleware-doc/montenegro
title: Introduction
---

# Fiscalization in Montenegro
This chapter expands on the information provided in the _General_ chapter by adding details specific to the fiscalization for Montenegro. This additional information is provided only where applicable. The remaining chapters, for which there is no extra information required, were omitted.

Legal regulations and further information can be found [on the website of the Montenegran tax authority](https://upravaprihoda.gov.me/rubrike/aktuelnosti/232806/Sve-o-ELEKTRONSKOJ-FISKALIZACIJI-na-jednom-mjestu.html).


<div class="alert alert--warning" role="alert">Please note that this information is only complete when combined with the <b>General</b> part. To implement the Middleware, users should get themselves familiar with the general information first and then refer to the country-specific details listed here.</div>
```

:::note

At the moment there is no fiskaltrust.Portal for the Montenegrin market. That means the Configuration of the Cashbox and the download of the Launcher have to be done manually. If you need help to getting started we are happy to assist you.

:::

2023-11-08 11:53 UTC, volllly approved these changes

2023-11-08 13:38 UTC, volllly approved these changes

2023-11-08 13:38 UTC, merged