archive definition modified in french appendix
fiskaltrust/interface-doc pull request #253
Opened 2023-03-06 06:57 UTC by Bluette-C-Riviere

- [ ] You've read the [Contributor Guide](https://github.com/fiskaltrust/.github/blob/main/CONTRIBUTING.md) and [Code of Conduct](https://github.com/fiskaltrust/.github/blob/main/CODE_OF_CONDUCT.md).
- [ ] You've included unit or integration tests for your change, where applicable.
- [ ] You've included inline docs for your change, where applicable.
- [ ] There's an open issue for the PR that you are making. If you'd like to propose a new feature or change, please open an issue to discuss the change or find an existing issue.

{Summary of the changes}

## Description

{Detail}

Fixes #{issue number}

2023-03-06 08:25 UTC, volllly requested changes

2023-03-06 08:25 UTC, volllly commented on doc/middleware-fr-boi-tva-decl-30-10-30/reference-tables/reference-tables.md
> +| `0x4652000000000015` | **Archive**<br />Has to be Signed<br />Sign: Yes<br />Chain and national numbering: A<br />Details: Will trigger a daily closing automatically.<br />Creates an archive starti
```suggestion
| `0x4652000000000015` | **Archive**<br />Has to be Signed<br />Sign: Yes<br />Chain and national numbering: A<br />Details: Will trigger a daily closing automatically.<br />Creates an archive starting with the first receipt of the queue (or first receipt after the last archive) until the last receipt before this request. It must not contain more than 365 days.<br />To retrieve the export as a zip-file (containing the certificate, ReceiptJournals and QueueItems), a normal `/journal`request has to be sent to the `ftJournalType`: `0x4652000000010010`. The value of `ftQueueRow` in the response of this ReceiptCase has to be sent in the `from`-parameter.<br />The content of the retrieved zip-file can be verified with the _ExportTool_ for France available on our [website](https://fiskaltrust.fr/taxAudit/fiskaltrust.TaxAuditorTool.zip). | 1.2                    |
```

2023-03-06 08:25 UTC, volllly commented on doc/middleware-fr-boi-tva-decl-30-10-30/reference-tables/reference-tables.md
> +2                    |
```suggestion
```

2023-03-08 08:19 UTC, forsthug approved these changes

2023-03-10 06:41 UTC, forsthug approved these changes

2023-03-10 06:53 UTC, merged