Update digital-receipt-instore-app.md
fiskaltrust/interface-doc pull request #285
Opened 2023-10-04 13:51 UTC by nholzberger97

Added POS API Helper and POS API configuration URL, added URL to download InStore App from App Center

- [ ] You've read the [Contributor Guide](https://github.com/fiskaltrust/.github/blob/main/CONTRIBUTING.md) and [Code of Conduct](https://github.com/fiskaltrust/.github/blob/main/CODE_OF_CONDUCT.md).
- [ ] You've included unit or integration tests for your change, where applicable.
- [ ] You've included inline docs for your change, where applicable.
- [ ] There's an open issue for the PR that you are making. If you'd like to propose a new feature or change, please open an issue to discuss the change or find an existing issue.

{Summary of the changes}

## Description

{Detail}

Fixes #{issue number}

2023-10-04 13:52 UTC, nholzberger97 commented
@fiskaltrust/team-poscreator-experience please merge, many thanks.

2023-10-09 08:15 UTC, mijomilicevic requested changes

2023-10-09 08:15 UTC, mijomilicevic commented on doc/digital-receipt/Instore-App/digital-receipt-instore-app.md
i would add an _<br / >_ for step 3 to have a linbreak after the screenshot (line 98)

2023-10-09 08:15 UTC, mijomilicevic commented on doc/digital-receipt/Instore-App/digital-receipt-instore-app.md
i think it should be "You can pair multiple InStore App installationS with one CashBox." in line 98

2023-10-09 08:58 UTC, nholzberger97 reviewed
added <br/> and missing s in row 98

2023-10-09 09:31 UTC, mijomilicevic approved these changes

2023-10-09 09:32 UTC, mijomilicevic approved these changes

2023-10-09 09:35 UTC, merged